### ISSUE TITLE
Replace wrong

### ISSUE THREAD

**Issue by bbday** [sd-soleaio/javascript-deobfuscator#3]
original:
```
_0xf2c21d['0'] = 0x808200,
_0xf2c21d['1'] = 0x8000,
_0xf2c21d[_0x3a8459(0x311)] = 0x8000,
```

after execution: (look like is simplify properties)
```
_0xf2c21d.0 = 8421888,
_0xf2c21d.1 = 32768,
_0xf2c21d[_0x3a8459(785)] = 32768,
```

obufuscator: obfuscator.io

I tried to use your old project to deobfuscate it but i have error about:
FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory

I would like to contact you but discord say i can't add you like friend

**Comment by sd-soleaio** [comment]
The website deobfuscate.io wasn't using the latest version, have updated it so that issue shouldn't occur.
