### ISSUE TITLE
Fails to deobfuscate

### ISSUE THREAD

**Issue by ThuGie** [sd-soleaio/javascript-deobfuscator#4]
I think its obfuscate.io i used your older deobfuscator it kind of worked. but replaced the info from the array to the wrong spots.
Yet this one doesnt seem to do anything.

https://pastebin.com/hSxmhrd8

If you could help find a solution for this, as i have a few files like this.
Thanks in advance.

**Comment by sd-soleaio** [comment]
This deobfuscator isn't specific to any obfuscator, instead more of a general purpose deobfuscator. As a result it's unlikely to have much effect on scripts that have been obfuscated with more complicated obfuscators. To deobfuscate those a deobfuscator specific to that obfuscator is required (like my old one but which is now deprecated).
